public enum IdleType
{
    ActTomato,
    ActCarrot,
    ActRadish,
    ActWatermelon,
    ActCorn,
    ActCow,
    ActChicken,
    ActPig,
    FactoryTomato,
    FactoryCarrot,
    FactoryRadish,
    FactoryWatermelon,
    FactoryCorn,
    FactoryCow,
    FactoryChicken,
    FactoryPig,
    Canteen
}
